[build]
    publish = "dist"
    command = "npm run build"

[dev]
    command = "npm run start"

[functions]
    directory = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[edge_functions]]
    function = "eleventy-edge"
    path = "/*"