import type { RemoveOptions } from "hebrew-transliteration";
import type { StructureOptions } from "../services/structureService";

export const default_remove_options: RemoveOptions = {
  PASEQ: false,
  MAQAF: false,
  SOF_PASUQ: false,
  NUN_HAFUKHA: false,
  PUNC_GERESH: false,
  PUNC_GERSHAYIM: false,
  MASORA_CIRCLE: false,
  LOWER_DOT: false,
  UPPER_DOT: false,
  ETNAHTA: true,
  SEGOLTA: true,
  SHALSHELET: true,
  ZAQEF_QATAN: true,
  ZAQEF_GADOL: true,
  TIPEHA: true,
  REVIA: true,
  ZARQA: true,
  PASHTA: true,
  YETIV: true,
  TEVIR: true,
  GERESH: true,
  GERESH_MUQDAM: true,
  GERSHAYIM: true,
  QARNEY_PARA: true,
  TELISHA_GEDOLA: true,
  PAZER: true,
  ATNAH_HAFUKH: true,
  MUNAH: true,
  MAHAPAKH: true,
  MERKHA: true,
  MERKHA_KEFULA: true,
  DARGA: true,
  QADMA: true,
  TELISHA_QETANA: true,
  YERAH_BEN_YOMO: true,
  OLE: true,
  ILUY: true,
  DEHI: true,
  ZINOR: true,
  SHEVA: false,
  HATAF_SEGOL: false,
  HATAF_PATAH: false,
  HATAF_QAMATS: false,
  HIRIQ: false,
  TSERE: false,
  SEGOL: false,
  PATAH: false,
  QAMATS: false,
  HOLAM: false,
  QUBUTS: false,
  DAGESH: false,
  METEG: false,
  RAFE: false,
  SHIN_DOT: false,
  SIN_DOT: false,
  QAMATS_QATAN: false,
};

export const default_structure_options: StructureOptions = {
  "05C3": "new_line",
  "0591": "new_line",
  "0592": "none",
  "0593": "none",
  "0594": "none",
  "0595": "none",
  "0596": "none",
  "0597": "none",
  "05AE": "none",
  "0599": "none",
  "059A": "none",
  "059B": "none",
  "059C": "none",
  "059E": "none",
  "05A1": "none",
  "059F": "none",
  "05A0": "none",
};
